
export const PRODUCTS_LOADING = 'PRODUCTS_LOADING'
export const ADD_PRODUCTS = 'ADD_PRODUCTS'
export const PRODUCTS_FAILED = 'PRODUCTS_FAILED'
export const SELECT_PRODUCT = 'SELECT_PRODUCT'
export const UNSELECT_PRODUCT = 'UNSELECT_PRODUCT'
export const CLEAR_CART = 'CLEAR_CART'